package com.songdice.export

import com.example.songdice.data.model.DiceParameter
import com.example.songdice.data.model.DiceState
import com.example.songdice.data.model.MusicalGenre
import com.example.songdice.data.model.SongArrangement

/**
 * Pure Kotlin AI Prompt generator formatting decoupled style & production tags
 * (Genre, Tempo, Instruments, Mood) and structural lyrics ([Verse 1], [Chorus], [Outro])
 * optimized for Suno AI, Udio, and Google Flow Music.
 */
object AIPromptFormatter {

    /**
     * Container for decoupled style and production metadata.
     */
    data class DecoupledStyleTags(
        val genre: String,
        val tempo: String,
        val instruments: List<String>,
        val mood: String,
        val production: List<String>
    )

    /**
     * Formats a complete AI Prompt text asset string from a [SongArrangement] and optional inputs.
     */
    fun formatAIPrompt(
        arrangement: SongArrangement,
        diceStates: Map<DiceParameter, DiceState> = emptyMap(),
        userStylePrompt: String = "",
        customLyrics: String? = null
    ): String {
        return formatAIPrompt(
            title = arrangement.title,
            genre = arrangement.genre,
            bpm = arrangement.bpm,
            key = arrangement.key,
            progression = arrangement.progression,
            diceStates = diceStates,
            userStylePrompt = userStylePrompt,
            customLyrics = customLyrics
        )
    }

    /**
     * Formats a complete AI Prompt text asset string from individual parameters.
     */
    fun formatAIPrompt(
        title: String,
        genre: String,
        bpm: Int,
        key: String = "C Major",
        progression: String = "I - V - vi - IV",
        diceStates: Map<DiceParameter, DiceState> = emptyMap(),
        userStylePrompt: String = "",
        customLyrics: String? = null
    ): String {
        val styleTags = extractStyleTags(genre, bpm, diceStates, userStylePrompt)
        val sb = StringBuilder()

        sb.appendLine("==================================================")
        sb.appendLine("            SONG DICE • AI PROMPT ASSET           ")
        sb.appendLine("==================================================")
        sb.appendLine()

        // 1. Decoupled Production & Style Tags
        sb.appendLine("[STYLE & PRODUCTION TAGS]")
        sb.appendLine("Genre: ${styleTags.genre}")
        sb.appendLine("Tempo: ${styleTags.tempo}")
        sb.appendLine("Instruments: ${styleTags.instruments.joinToString(", ")}")
        sb.appendLine("Mood & Aesthetic: ${styleTags.mood}")
        sb.appendLine("Production Style: ${styleTags.production.joinToString(", ")}")
        sb.appendLine()

        // 2. Platform Specific Prompt Blocks
        sb.appendLine("[PLATFORM PROMPTS]")

        // Suno AI Prompt Block
        sb.appendLine("--- Suno AI Prompt ---")
        val sunoStyle = "[Style: ${styleTags.genre}, ${styleTags.tempo}, ${styleTags.instruments.joinToString(", ")}, ${styleTags.mood}]"
        sb.appendLine(sunoStyle)
        sb.appendLine()

        // Udio AI Tag Block
        sb.appendLine("--- Udio Prompt Tags ---")
        val udioTags = listOf(
            styleTags.genre.lowercase(),
            styleTags.tempo.lowercase(),
            styleTags.mood.lowercase()
        ) + styleTags.instruments.map { it.lowercase() } + styleTags.production.map { it.lowercase() }
        sb.appendLine(udioTags.joinToString(", "))
        sb.appendLine()

        // Google Flow Music Prompt
        sb.appendLine("--- Google Flow Music Prompt ---")
        val flowMusic = "Genre: ${styleTags.genre} | Tempo: ${styleTags.tempo} | Key: $key | Instrumentation: ${styleTags.instruments.joinToString(", ")} | Mood: ${styleTags.mood}"
        sb.appendLine(flowMusic)
        sb.appendLine()

        // 3. Structural Lyrics Block
        sb.appendLine("[STRUCTURAL LYRICS]")
        val formattedLyrics = if (!customLyrics.isNullOrBlank()) {
            formatLyrics(customLyrics)
        } else {
            generateProceduralLyrics(title, genre, key, progression)
        }
        sb.appendLine(formattedLyrics)

        sb.appendLine("==================================================")
        sb.appendLine("Generated by Song Dice AIPromptFormatter")
        sb.appendLine("==================================================")

        return sb.toString()
    }

    /**
     * Extracts decoupled style tags based on genre, tempo, dice states, and style prompt.
     */
    fun extractStyleTags(
        genre: String,
        bpm: Int,
        diceStates: Map<DiceParameter, DiceState> = emptyMap(),
        userStylePrompt: String = ""
    ): DecoupledStyleTags {
        val drumRhythm = diceStates[DiceParameter.DRUM_RHYTHM]?.value ?: ""
        val bassPattern = diceStates[DiceParameter.BASS_PATTERN]?.value ?: ""
        val chordRhythm = diceStates[DiceParameter.CHORD_RHYTHM]?.value ?: ""
        val melodyContour = diceStates[DiceParameter.MELODY_CONTOUR]?.value ?: ""

        val instruments = mutableListOf<String>()

        // Map Instruments based on genre and dice parameters
        when {
            genre.contains("Synthwave", ignoreCase = true) -> {
                instruments.addAll(listOf("Analog Synthesizer", "Synth Bass", "80s Drum Machine", "Arpeggiated Lead"))
            }
            genre.contains("Lofi", ignoreCase = true) -> {
                instruments.addAll(listOf("Dusty Keys", "Sub Bass", "Vinyl Crackle Drums", "Muted Electric Guitar"))
            }
            genre.contains("Pop", ignoreCase = true) -> {
                instruments.addAll(listOf("Acoustic Piano", "Electric Bass", "Modern Pop Kick", "Bright Synth Lead"))
            }
            genre.contains("Rock", ignoreCase = true) -> {
                instruments.addAll(listOf("Overdriven Guitar", "Electric Bass", "Punchy Acoustic Drums", "Organ"))
            }
            genre.contains("EDM", ignoreCase = true) -> {
                instruments.addAll(listOf("Sawtooth Pluck", "Sub Bass Drop", "Four-on-the-Floor Kick", "Vocal Chops"))
            }
            else -> {
                instruments.addAll(listOf("Piano", "Bass", "Drums", "Synthesizer"))
            }
        }

        if (bassPattern.contains("Slap", ignoreCase = true)) instruments.add("Slap Bass")
        if (drumRhythm.contains("Trap", ignoreCase = true)) instruments.add("808 Hi-Hats")

        val tempoTag = "$bpm BPM"

        val mood = when {
            userStylePrompt.contains("dark", ignoreCase = true) || userStylePrompt.contains("sad", ignoreCase = true) -> "Melancholic, Atmospheric, Moody"
            userStylePrompt.contains("upbeat", ignoreCase = true) || userStylePrompt.contains("happy", ignoreCase = true) -> "Upbeat, Energetic, Euphoric"
            genre.contains("Lofi", ignoreCase = true) -> "Chill, Nostalgic, Relaxed"
            genre.contains("Synthwave", ignoreCase = true) -> "Retro-Futuristic, Neon, Energetic"
            genre.contains("Rock", ignoreCase = true) -> "Raw, Driving, Dynamic"
            else -> "Captivating, Dynamic, Rhythmic"
        }

        val production = listOf(
            "High Definition Master",
            "Stereo Width",
            "Clear Mix",
            "Dynamic Range"
        )

        return DecoupledStyleTags(
            genre = genre,
            tempo = tempoTag,
            instruments = instruments.distinct(),
            mood = mood,
            production = production
        )
    }

    /**
     * Formats custom lyrics string ensuring standard [Verse 1], [Chorus], [Outro] structure.
     */
    fun formatLyrics(rawLyrics: String): String {
        if (rawLyrics.contains("[Verse") || rawLyrics.contains("[Chorus")) {
            return rawLyrics
        }

        val lines = rawLyrics.lines().filter { it.isNotBlank() }
        val sb = StringBuilder()

        if (lines.size <= 4) {
            sb.appendLine("[Verse 1]")
            lines.forEach { sb.appendLine(it) }
            sb.appendLine()
            sb.appendLine("[Chorus]")
            lines.forEach { sb.appendLine(it) }
        } else {
            val mid = lines.size / 2
            sb.appendLine("[Verse 1]")
            lines.take(mid).forEach { sb.appendLine(it) }
            sb.appendLine()
            sb.appendLine("[Chorus]")
            lines.drop(mid).forEach { sb.appendLine(it) }
            sb.appendLine()
            sb.appendLine("[Outro]")
            lines.takeLast(2).forEach { sb.appendLine(it) }
        }

        return sb.toString().trimEnd()
    }

    /**
     * Generates clean procedural lyrics with [Verse 1], [Chorus], and [Outro] tags.
     */
    fun generateProceduralLyrics(
        title: String,
        genre: String,
        key: String,
        progression: String
    ): String {
        val sb = StringBuilder()

        sb.appendLine("[Verse 1]")
        sb.appendLine("Walking through the static sound,")
        sb.appendLine("Echoes rising from the ground.")
        sb.appendLine("Rolling dice under twilight skies,")
        sb.appendLine("In the key of $key, the rhythm stays alive.")
        sb.appendLine()

        sb.appendLine("[Chorus]")
        sb.appendLine("$title, hear the melody ring,")
        sb.appendLine("Through $progression, we sing.")
        sb.appendLine("Bound by the frequency, lost in the beat,")
        sb.appendLine("Song Dice energy taking to the street.")
        sb.appendLine()

        sb.appendLine("[Verse 2]")
        sb.appendLine("Fading shadows turn to light,")
        sb.appendLine("Synthesizers pulse through the night.")
        sb.appendLine("Every measure holds a spark,")
        sb.appendLine("Guiding us out from the dark.")
        sb.appendLine()

        sb.appendLine("[Outro]")
        sb.appendLine("Fade into the twilight tone...")
        sb.appendLine("Harmonies echo back home.")

        return sb.toString().trimEnd()
    }
}
