package com.songdice.export

import com.example.songdice.data.model.DiceParameter
import com.example.songdice.data.model.DiceState
import com.example.songdice.data.model.SongArrangement

/**
 * Pure Kotlin Lead Sheet generator formatting metadata, chord progressions,
 * and ASCII keyboard diagrams for left-hand (LH) and right-hand (RH) voicings.
 */
object LeadSheetFormatter {

    private val NOTE_NAMES = listOf("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")

    /**
     * Data representation for a chord voicing with Left-Hand (LH) and Right-Hand (RH) notes.
     */
    data class ChordVoicing(
        val chordName: String,
        val lhNotes: List<String>,
        val rhNotes: List<String>
    )

    /**
     * Converts a MIDI pitch number (0-127) to a note name with octave (e.g. 60 -> "C4").
     */
    fun pitchToNoteName(pitch: Int): String {
        val noteName = NOTE_NAMES[(pitch % 12 + 12) % 12]
        val octave = (pitch / 12) - 1
        return "$noteName$octave"
    }

    /**
     * Formats a complete Lead Sheet text from a [SongArrangement] and optional [diceStates].
     */
    fun formatLeadSheet(
        arrangement: SongArrangement,
        diceStates: Map<DiceParameter, DiceState> = emptyMap()
    ): String {
        return formatLeadSheet(
            title = arrangement.title,
            genre = arrangement.genre,
            key = arrangement.key,
            bpm = arrangement.bpm,
            progression = arrangement.progression,
            diceStates = diceStates
        )
    }

    /**
     * Formats a complete Lead Sheet text from raw parameters.
     */
    fun formatLeadSheet(
        title: String,
        genre: String,
        key: String,
        bpm: Int,
        progression: String,
        diceStates: Map<DiceParameter, DiceState> = emptyMap()
    ): String {
        val sb = StringBuilder()

        sb.appendLine("==================================================")
        sb.appendLine("            SONG DICE • LEAD SHEET               ")
        sb.appendLine("==================================================")
        sb.appendLine()

        // 1. Song Metadata
        sb.appendLine("[SONG METADATA]")
        sb.appendLine("Title: $title")
        sb.appendLine("Genre: $genre")
        sb.appendLine("Key: $key")
        sb.appendLine("Tempo: $bpm BPM")
        sb.appendLine("Chord Progression: $progression")
        if (diceStates.isNotEmpty()) {
            sb.appendLine("Dice Parameters:")
            diceStates.forEach { (param, state) ->
                val lock = if (state.isLocked) "[LOCKED]" else "[ROLLED]"
                sb.appendLine("  - ${param.displayName}: ${state.value} $lock")
            }
        }
        sb.appendLine()

        // 2. Song Structure & Progression Sequence
        sb.appendLine("[SONG STRUCTURE & CHORD PROGRESSION]")
        val chordList = parseProgressionChords(progression, key)
        val measureBar = chordList.joinToString(" | ", prefix = "| ", postfix = " |")
        sb.appendLine("Form: [Intro] -> [Verse] -> [Chorus] -> [Outro]")
        sb.appendLine("Main Harmonic Loop:")
        sb.appendLine(measureBar)
        sb.appendLine()

        // 3. ASCII Keyboard Voicings
        sb.appendLine("[VOICINGS & ASCII KEYBOARD DIAGRAMS]")
        val voicings = generateVoicings(chordList, key)

        voicings.forEach { voicing ->
            sb.appendLine("Chord: ${voicing.chordName}")
            sb.appendLine("  Left-Hand (LH) Bass:   ${voicing.lhNotes.joinToString(" ")}")
            sb.appendLine("  Right-Hand (RH) Chord: ${voicing.rhNotes.joinToString(" ")}")
            sb.appendLine("  ASCII Keyboard Diagram:")
            sb.append(generateAsciiKeyboard(voicing.lhNotes, voicing.rhNotes))
            sb.appendLine()
        }

        sb.appendLine("==================================================")
        sb.appendLine("Generated by Song Dice LeadSheetFormatter")
        sb.appendLine("==================================================")

        return sb.toString()
    }

    /**
     * Parses a chord progression string into a list of display chord names.
     */
    fun parseProgressionChords(progression: String, key: String): List<String> {
        val items = progression.split("-", ",", ">", "|").map { it.trim() }.filter { it.isNotEmpty() }
        if (items.isEmpty()) return listOf(key)

        val isMinorKey = key.contains("Minor", ignoreCase = true) || key.contains("m", ignoreCase = true)
        val rootNote = extractRootNote(key)

        return items.map { token ->
            if (token.contains("Major") || token.contains("Minor") || token.contains("m ") || token.contains("7")) {
                token
            } else {
                romanToChordName(token, rootNote, isMinorKey)
            }
        }
    }

    private fun extractRootNote(key: String): String {
        val tokens = key.trim().split(" ")
        return if (tokens.isNotEmpty()) tokens[0] else "C"
    }

    /**
     * Maps Roman numerals to Chord Names in a key.
     */
    private fun romanToChordName(roman: String, keyRoot: String, isMinorKey: Boolean): String {
        val rootIndex = NOTE_NAMES.indexOfFirst { it.equals(keyRoot, ignoreCase = true) }.let { if (it < 0) 0 else it }
        val cleanRoman = roman.replace(Regex("[^a-zA-Z0-9]"), "")

        val semitoneOffset = when (cleanRoman.uppercase()) {
            "I" -> 0
            "II" -> if (isMinorKey) 2 else 2
            "III" -> if (isMinorKey) 3 else 4
            "IV" -> 5
            "V" -> 7
            "VI" -> if (isMinorKey) 8 else 9
            "VII" -> if (isMinorKey) 10 else 11
            else -> 0
        }

        val chordRoot = NOTE_NAMES[(rootIndex + semitoneOffset) % 12]
        val isMinorChord = cleanRoman.firstOrNull()?.isLowerCase() == true || isMinorKey && (cleanRoman.uppercase() == "I" || cleanRoman.uppercase() == "IV" || cleanRoman.uppercase() == "V")
        val quality = if (isMinorChord) "m" else ""

        return "$chordRoot$quality"
    }

    /**
     * Generates Left-Hand (LH) and Right-Hand (RH) chord voicings.
     */
    fun generateVoicings(chords: List<String>, key: String): List<ChordVoicing> {
        return chords.map { chordName ->
            val root = chordName.replace("m", "").replace("7", "").replace("maj", "").trim()
            val rootIndex = NOTE_NAMES.indexOfFirst { it.equals(root, ignoreCase = true) }.let { if (it < 0) 0 else it }
            val isMinor = chordName.contains("m") && !chordName.contains("maj")

            val thirdOffset = if (isMinor) 3 else 4
            val fifthOffset = 7

            val rootNoteName = NOTE_NAMES[rootIndex]
            val thirdNoteName = NOTE_NAMES[(rootIndex + thirdOffset) % 12]
            val fifthNoteName = NOTE_NAMES[(rootIndex + fifthOffset) % 12]

            ChordVoicing(
                chordName = chordName,
                lhNotes = listOf("${rootNoteName}2", "${rootNoteName}3"),
                rhNotes = listOf("${rootNoteName}4", "${thirdNoteName}4", "${fifthNoteName}4")
            )
        }
    }

    /**
     * Renders a 1-octave ASCII piano keyboard diagram with active note indicators.
     */
    fun generateAsciiKeyboard(lhNotes: List<String>, rhNotes: List<String>): String {
        val activeLh = lhNotes.map { it.replace(Regex("[0-9]"), "").uppercase() }.toSet()
        val activeRh = rhNotes.map { it.replace(Regex("[0-9]"), "").uppercase() }.toSet()

        val sb = StringBuilder()
        sb.appendLine("  +---+---+---+---+---+---+---+")
        sb.appendLine("  |   |C# |D# |   |F# |G# |A# |")
        sb.appendLine("  |   |___|___|   |___|___|___|")
        sb.appendLine("  | C | D | E | F | G | A | B |")
        sb.appendLine("  +---+---+---+---+---+---+---+")

        // Render LH / RH indicators below the keys
        val keys = listOf("C", "D", "E", "F", "G", "A", "B")
        val lhLine = keys.joinToString("|", prefix = "  LH: |", postfix = "|") { key ->
            if (activeLh.contains(key)) " * " else "   "
        }
        val rhLine = keys.joinToString("|", prefix = "  RH: |", postfix = "|") { key ->
            if (activeRh.contains(key)) " * " else "   "
        }

        sb.appendLine(lhLine)
        sb.appendLine(rhLine)
        return sb.toString()
    }
}
